version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: vaggo
    environment:
      POSTGRES_DB: VaggoDB
      POSTGRES_USER: vaggo
      POSTGRES_PASSWORD: vaggo123
    ports:
      - "5431:5432"
    restart: always
